# Generated by Django 5.1.2 on 2025-07-13 14:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_ckd', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-created_at'], 'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
        migrations.RemoveField(
            model_name='patient',
            name='id',
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(error_messages={'unique': 'A patient with this phone number already exists.'}, max_length=11, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid Bangladeshi mobile number (e.g. 01712345678)', regex='^01[3-9]\\d{8}$')]),
        ),
    ]
