# Generated by Django 5.1.2 on 2025-07-13 15:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_ckd', '0002_alter_patient_options_remove_patient_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(error_messages={'unique': 'A patient with this phone number already exists.'}, max_length=11, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid Bangladeshi mobile number (e.g. 01712345678)', regex='^1[3-9]\\d{8}$')]),
        ),
    ]
