# Generated by Django 5.1.2 on 2025-07-14 07:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_ckd', '0004_alter_patient_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='albumin',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='bacteria',
            field=models.CharField(blank=True, choices=[('present', 'Present'), ('notpresent', 'Not Present')], max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_glucose',
            field=models.FloatField(blank=True, null=True, verbose_name='Blood Glucose (mg/dL)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_urea',
            field=models.FloatField(blank=True, null=True, verbose_name='Blood Urea (mg/dL)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='coronary_artery_disease',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
        migrations.AddField(
            model_name='patient',
            name='hemoglobin',
            field=models.FloatField(blank=True, null=True, verbose_name='Hemoglobin (g/dL)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='packed_cell_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='potassium',
            field=models.FloatField(blank=True, null=True, verbose_name='Potassium (mEq/L)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='pus_cell',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('abnormal', 'Abnormal')], max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='pus_cell_clumps',
            field=models.CharField(blank=True, choices=[('present', 'Present'), ('notpresent', 'Not Present')], max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='red_blood_cell',
            field=models.FloatField(blank=True, null=True, verbose_name='RBC (millions/cmm)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='red_blood_cells',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('abnormal', 'Abnormal')], max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='serum_creatinine',
            field=models.FloatField(blank=True, null=True, verbose_name='Serum Creatinine (mg/dL)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='sodium',
            field=models.FloatField(blank=True, null=True, verbose_name='Sodium (mEq/L)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='specific_gravity',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(1.03)]),
        ),
        migrations.AddField(
            model_name='patient',
            name='sugar',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='white_blood_cell',
            field=models.FloatField(blank=True, null=True, verbose_name='WBC (cells/cmm)'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='lower_bp',
            field=models.PositiveIntegerField(verbose_name='Lower BP (mmHg)'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='upper_bp',
            field=models.PositiveIntegerField(verbose_name='Upper BP (mmHg)'),
        ),
    ]
