# Generated by Django 5.1.2 on 2025-06-24 18:26

import student.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(default=None, null=True, upload_to=student.models.student_directory_name),
        ),
    ]
