a='this is string'
b="this is also string"
print(a)
print(type(a))
print(b)
print(type(b))
print(a+b)
print(len(a))
x = "hello"
y = "world"
print(x.title())
print(x.upper())
print(x.lower())
print(x.capitalize())
print(x.replace('h','j'))
print(x.swapcase())
print(x.isalpha())
print(x.isdigit())
print(x.isalnum())
print(x.islower())
print(x.isupper())
print(x.isspace())
print(x.startswith('h'))
print(x.endswith('o'))
print(x.find('e'))
print(x.count('l'))
