# Generated by Django 5.2.5 on 2025-08-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('role', models.CharField(choices=[('admin', 'admin'), ('teacher', 'Teacher'), ('student', 'Student')], max_length=10)),
                ('mobile_no', models.CharField(blank=True, max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
